Repository mobven/YummyCompose, pull requests merged in 2023-08, with the labels that each got.

#12 ✨[FEATURE] - Input Fields.
  designsystem/src/main/java/com/mobven/designsystem/components/common/Ext.kt
  designsystem/src/main/java/com/mobven/designsystem/components/inputs/PasswordInputField.kt
  designsystem/src/main/java/com/mobven/designsystem/components/inputs/PhoneNumberField.kt
  designsystem/src/main/res/drawable/eye_slash.xml
Labels: documentation, enhancement

#19 [FIX] - Remove bottom margin
  designsystem/src/main/java/com/mobven/designsystem/components/cards/RestaurantWithLocationCard.kt
Labels: bug

#20 [FEATURE] - Card 3 component added.
  designsystem/src/main/java/com/mobven/designsystem/components/common/CardThree.kt
  designsystem/src/main/res/drawable/card_three.png
  designsystem/src/main/res/drawable/ic_plus_28.xml
Labels: enhancement
